### ISSUE TITLE
Simplify build: use go:embed instead of `go generate`

### ISSUE THREAD

**Issue by laszlocph** [gimlet-io/gimlet-cli#16]
With go 1.16 code generation it is not needed anymore to embed the `web/dist` for the build in UI of `gimlet chart configure`

The task is to use the native bo embed feature (https://blog.carlmjohnson.net/post/2021/how-to-use-go-embed/) instead of the [make generate-backend](https://github.com/gimlet-io/gimlet-cli/blob/main/Makefile#L19) make target.

**Comment by tullo** [comment]
I'll have a go with it.

**Comment by tullo** [comment]
@laszlocph could you test the PR when you get time. The GH action currently fails with `Error: The ssh-private-key argument is empty. Maybe the secret has not been configured, or you are using a wrong secret name in your workflow file.`. I guess you have that key configured.

**Comment by laszlocph** [comment]
Thank you @tullo for the PR. It was spot on. The build is failing on contributor PRs due to #20 which we are going to address asap.
