### ISSUE TITLE
Fix Helm dependency

### ISSUE THREAD

**Issue by laszlocph** [gimlet-io/gimlet-cli#18]
https://github.com/helm/helm/issues/9354 has been fixed, so we should clean up our [go.mod](https://github.com/gimlet-io/gimlet-cli/blob/main/go.mod#L35)

**Comment by soniasingla** [comment]
@laszlocph I debugged this issue, and it seems we need to keep the `replace` part or am I missing something?

**Comment by laszlocph** [comment]
I think we should wait for https://github.com/helm/helm/pull/9492 to be merged.

They closed my linked issue, but the PR is not merged yet..
Ideally the PR should remove the need for the `replace`.

Let's wait until the PR is merged.

**Comment by soniasingla** [comment]
Amazing, thanks for the update!

**Comment by laszlocph** [comment]
go.mod cleaned up https://github.com/gimlet-io/gimlet-cli/commit/0fa13ce8ae25955926d644483163aa80674108c2
