### ISSUE TITLE
CLI Broken

### ISSUE THREAD

**Issue by appinteractive** [gimlet-io/gimlet-cli#51]
I did install the latest version of gimlet cli like discribed, when trying to run I get following output:

```sh
gimlet
/usr/local/bin/gimlet: line 1: Not: command not found
```

I'm on a Mac Book Pro M1

**Comment by appinteractive** [comment]
Seems Like the latest stable version is not ARM Compatible

**Comment by laszlocph** [comment]
Should be fine. I will make a release tomorrow.

**Comment by laszlocph** [comment]
v0.12.1 has the M1 support
